// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDndQZBDjYBi-uXUwSOUZdejqgKpGO10VU',
    appId: '1:107093371713:web:5d6c9b05b99761174c4fc0',
    messagingSenderId: '107093371713',
    projectId: 'ottt-ab0fe',
    authDomain: 'ottt-ab0fe.firebaseapp.com',
    storageBucket: 'ottt-ab0fe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBPH23I3fWh27jZ1GBubgwo2od7mMtWgo',
    appId: '1:107093371713:android:5894f7f18004e2464c4fc0',
    messagingSenderId: '107093371713',
    projectId: 'ottt-ab0fe',
    storageBucket: 'ottt-ab0fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAey5z8uSfJkw6iWbf_x2xi9NZ-iS_FBKU',
    appId: '1:107093371713:ios:0d040d8cf08d22974c4fc0',
    messagingSenderId: '107093371713',
    projectId: 'ottt-ab0fe',
    storageBucket: 'ottt-ab0fe.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAey5z8uSfJkw6iWbf_x2xi9NZ-iS_FBKU',
    appId: '1:107093371713:ios:0d040d8cf08d22974c4fc0',
    messagingSenderId: '107093371713',
    projectId: 'ottt-ab0fe',
    storageBucket: 'ottt-ab0fe.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDndQZBDjYBi-uXUwSOUZdejqgKpGO10VU',
    appId: '1:107093371713:web:84cf2ed57be79ee04c4fc0',
    messagingSenderId: '107093371713',
    projectId: 'ottt-ab0fe',
    authDomain: 'ottt-ab0fe.firebaseapp.com',
    storageBucket: 'ottt-ab0fe.appspot.com',
  );
}
