name: mathuram
description: "A new Flutter project."
publish_to: 'none' # Prevent accidental publishing

version: 1.0.2+3



environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.1.0
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.0.0
  font_awesome_flutter: ^10.0.0
  url_launcher: ^6.3.0
  http: ^1.4.0
  flutter_launcher_icons: ^0.14.3
  path_provider: ^2.1.2
  share_plus: ^11.0.0
  permission_handler: ^12.0.0+1
  pinput: ^5.0.1
  smart_auth: ^3.2.0
  device_info_plus: ^11.4.0
  geolocator: ^11.0.0


  shared_preferences: ^2.5.3
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  google_sign_in: ^6.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: 'assets/logo.png'

flutter:
  uses-material-design: true

  assets:
    - assets/
